# Generated by Django 4.0.5 on 2022-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='suffix',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
