# Generated by Django 4.0.5 on 2022-07-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='suffix',
        ),
    ]
