# Generated by Django 4.1.1 on 2022-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
    ]
