# Generated by Django 4.1.1 on 2022-09-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest', to='products.producthistory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lowest_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lowest', to='products.producthistory'),
        ),
    ]
