# Generated by Django 4.1.1 on 2022-10-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_highest_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest', to='products.producthistory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
