# Generated by Django 3.2.9 on 2021-11-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('path', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ko_name', models.CharField(max_length=30)),
                ('en_name', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowest.brands')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='lowest.history')),
                ('highest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest', to='lowest.history')),
                ('lowest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowest', to='lowest.history')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowest.products'),
        ),
    ]
