# Generated by Django 4.0.5 on 2022-07-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requested_price', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('url', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_product', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_producthistory', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='highest_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_product', to='products.producthistory'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_product', to='products.producthistory'),
        ),
        migrations.AddField(
            model_name='product',
            name='lowest_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowest_product', to='products.producthistory'),
        ),
    ]
