# Generated by Django 4.0.5 on 2022-07-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_category_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='highest_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_product', to='products.producthistory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_product', to='products.producthistory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lowest_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowest_product', to='products.producthistory'),
        ),
    ]
