# Generated by Django 4.0.5 on 2022-08-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='requested_price',
            new_name='retail_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producthistory', to='products.product'),
        ),
    ]
